# Generated by Django 5.1.5 on 2025-04-18 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('reviewed', 'Reviewed'), ('interview_scheduled', 'Interview Scheduled'), ('interviewed', 'Interviewed'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='applied', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('hires_needed', models.PositiveIntegerField(default=1)),
                ('country', models.CharField(max_length=100)),
                ('language', models.CharField(default='English', max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('internship', 'Internship')], max_length=50)),
                ('contract_length', models.CharField(blank=True, max_length=100)),
                ('schedule', models.CharField(blank=True, max_length=255)),
                ('pay', models.CharField(blank=True, max_length=100)),
                ('supplemental_pay', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('pre_screening', models.TextField(blank=True)),
                ('require_resume', models.BooleanField(default=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('expected_start_date', models.DateField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('applications', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('interviewer', models.CharField(max_length=255)),
                ('location_or_link', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('pass', 'Pass'), ('fail', 'Fail'), ('reschedule', 'Reschedule')], default='pending', max_length=50)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='jobs.candidate')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='jobs.job'),
        ),
    ]
