# Generated by Django 5.1.5 on 2025-04-03 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text="User's first name", max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, help_text="User's last name", max_length=100, null=True)),
                ('username_description', models.TextField(blank=True, help_text='A short description about the user', null=True)),
                ('cv', models.FileField(blank=True, help_text="User's CV in PDF format", null=True, upload_to='cv/')),
                ('languages', models.CharField(blank=True, help_text='Comma-separated list of languages', max_length=255, null=True)),
                ('current_job', models.CharField(blank=True, help_text='Current job title or description of unemployment status', max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
