# Generated by Django 5.1.5 on 2025-03-02 08:16

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('project_description', models.CharField(max_length=600)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('link_url', models.CharField(max_length=600)),
                ('github_url', models.CharField(max_length=600)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(verbose_name=models.CharField(blank=True, max_length=5)), size=None)),
                ('image', models.ImageField(upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
