# Generated by Django 5.1.1 on 2024-09-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_rename_description_todo_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='project_description',
            field=models.CharField(max_length=500),
        ),
    ]
